### ISSUE TITLE
Create RPM package

### ISSUE THREAD

**Issue by hifly81** [jrnd-io/jr#94]

**Comment by giannisalinetti** [comment]
I am working on the rpm specfile for Fedora 40 (but it can be suitable for RHEL too). 

To install the templates from an rpm file we need a system-specific path instead of a user-specific one. The solution of using XDG standard dirs can be suitable. The `XDG_DATA_DIRS`, set to /usr/share should be used, followed by user-specific path with `XDG_CONFIG_HOME` or `XDG_DATA_HOME`, depending on how we consider template files (config or data).
More details here: https://specifications.freedesktop.org/basedir-spec/latest/index.html

The release submission for Fedora 40 implies the usage of `fedpkg` tool while the submission itself is based on the following process: https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/

**Comment by giannisalinetti** [comment]
@hifly81 please refer to PR #169 for the rpm spec file.

**Comment by giannisalinetti** [comment]
Extra note: the spec files must be changed on every release since the `Version` field must report the exact version of the release.
